<?php

// Data functions (insert, update, delete, form) for table concejo2019vallecalivotos

// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

function concejo2019vallecalivotos_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('concejo2019vallecalivotos');
	if(!$arrPerm['insert']) return false;

	$data = [
		'MESA_' => Request::val('MESA_', ''),
		'CANDIDATO' => Request::val('CANDIDATO', ''),
		'VOTOS' => Request::val('VOTOS', ''),
	];

	if($data['CVOTOS'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'CVOTOS': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['CANDIDATO'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'CANDIDATO': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['VOTOS'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'VOTOS': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: concejo2019vallecalivotos_before_insert
	if(function_exists('concejo2019vallecalivotos_before_insert')) {
		$args = [];
		if(!concejo2019vallecalivotos_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('concejo2019vallecalivotos', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = $data['CVOTOS'];

	// automatic PUESTO if passed as filterer
	if(Request::val('filterer_PUESTO')) {
		sql("UPDATE `concejo2019vallecalivotos` SET `PUESTO`='" . makeSafe(Request::val('filterer_PUESTO')) . "' WHERE `CVOTOS`='" . makeSafe($recID, false) . "'", $eo);
	}

	// automatic PARTIDO if passed as filterer
	if(Request::val('filterer_PARTIDO')) {
		sql("UPDATE `concejo2019vallecalivotos` SET `PARTIDO`='" . makeSafe(Request::val('filterer_PARTIDO')) . "' WHERE `CVOTOS`='" . makeSafe($recID, false) . "'", $eo);
	}

	update_calc_fields('concejo2019vallecalivotos', $recID, calculated_fields()['concejo2019vallecalivotos']);

	// hook: concejo2019vallecalivotos_after_insert
	if(function_exists('concejo2019vallecalivotos_after_insert')) {
		$res = sql("SELECT * FROM `concejo2019vallecalivotos` WHERE `CVOTOS`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!concejo2019vallecalivotos_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('concejo2019vallecalivotos', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) concejo2019vallecalivotos_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function concejo2019vallecalivotos_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function concejo2019vallecalivotos_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('concejo2019vallecalivotos', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: concejo2019vallecalivotos_before_delete
	if(function_exists('concejo2019vallecalivotos_before_delete')) {
		$args = [];
		if(!concejo2019vallecalivotos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `concejo2019vallecalivotos` WHERE `CVOTOS`='{$selected_id}'", $eo);

	// hook: concejo2019vallecalivotos_after_delete
	if(function_exists('concejo2019vallecalivotos_after_delete')) {
		$args = [];
		concejo2019vallecalivotos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='concejo2019vallecalivotos' AND `pkValue`='{$selected_id}'", $eo);
}

function concejo2019vallecalivotos_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('concejo2019vallecalivotos', $selected_id, 'edit')) return false;

	$data = [
		'MESA_' => Request::val('MESA_', ''),
		'CANDIDATO' => Request::val('CANDIDATO', ''),
		'VOTOS' => Request::val('VOTOS', ''),
	];

	if($data['CVOTOS'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'CVOTOS': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['CANDIDATO'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'CANDIDATO': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['VOTOS'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'VOTOS': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('concejo2019vallecalivotos', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: concejo2019vallecalivotos_before_update
	if(function_exists('concejo2019vallecalivotos_before_update')) {
		$args = ['old_data' => $old_data];
		if(!concejo2019vallecalivotos_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'concejo2019vallecalivotos', 
		backtick_keys_once($set), 
		['`CVOTOS`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="concejo2019vallecalivotos_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['CVOTOS'];
	$newID = $data['CVOTOS'];

	$eo = ['silentErrors' => true];

	update_calc_fields('concejo2019vallecalivotos', $data['selectedID'], calculated_fields()['concejo2019vallecalivotos']);

	// hook: concejo2019vallecalivotos_after_update
	if(function_exists('concejo2019vallecalivotos_after_update')) {
		$res = sql("SELECT * FROM `concejo2019vallecalivotos` WHERE `CVOTOS`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['CVOTOS'];
		$args = ['old_data' => $old_data];
		if(!concejo2019vallecalivotos_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "', `pkValue`='{$data['CVOTOS']}' WHERE `tableName`='concejo2019vallecalivotos' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);

	// if PK value changed, update $selected_id
	$selected_id = $newID;
}

function concejo2019vallecalivotos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('concejo2019vallecalivotos');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_PUESTO = Request::val('filterer_PUESTO');
	$filterer_PARTIDO = Request::val('filterer_PARTIDO');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: PUESTO
	$combo_PUESTO = new DataCombo;
	// combobox: PARTIDO
	$combo_PARTIDO = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('concejo2019vallecalivotos', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('concejo2019vallecalivotos', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('concejo2019vallecalivotos', $selected_id, 'delete');

		$res = sql("SELECT * FROM `concejo2019vallecalivotos` WHERE `CVOTOS`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'concejo2019vallecalivotos_view.php', false);
		}
		$combo_PUESTO->SelectedData = $row['PUESTO'];
		$combo_PARTIDO->SelectedData = $row['PARTIDO'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_PUESTO->SelectedData = $filterer_PUESTO;
		$combo_PARTIDO->SelectedData = $filterer_PARTIDO;
	}
	$combo_PUESTO->HTML = '<span id="PUESTO-container' . $rnd1 . '"></span><input type="hidden" name="PUESTO" id="PUESTO' . $rnd1 . '" value="' . html_attr($combo_PUESTO->SelectedData) . '">';
	$combo_PUESTO->MatchText = '<span id="PUESTO-container-readonly' . $rnd1 . '"></span><input type="hidden" name="PUESTO" id="PUESTO' . $rnd1 . '" value="' . html_attr($combo_PUESTO->SelectedData) . '">';
	$combo_PARTIDO->HTML = '<span id="PARTIDO-container' . $rnd1 . '"></span><input type="hidden" name="PARTIDO" id="PARTIDO' . $rnd1 . '" value="' . html_attr($combo_PARTIDO->SelectedData) . '">';
	$combo_PARTIDO->MatchText = '<span id="PARTIDO-container-readonly' . $rnd1 . '"></span><input type="hidden" name="PARTIDO" id="PARTIDO' . $rnd1 . '" value="' . html_attr($combo_PARTIDO->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_PUESTO__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['PUESTO'] : htmlspecialchars($filterer_PUESTO, ENT_QUOTES)); ?>"};
		AppGini.current_PARTIDO__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['PARTIDO'] : htmlspecialchars($filterer_PARTIDO, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(PUESTO_reload__RAND__) == 'function') PUESTO_reload__RAND__();
				if(typeof(PARTIDO_reload__RAND__) == 'function') PARTIDO_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function PUESTO_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#PUESTO-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_PUESTO__RAND__.value, t: 'concejo2019vallecalivotos', f: 'PUESTO' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="PUESTO"]').val(resp.results[0].id);
							$j('[id=PUESTO-container-readonly__RAND__]').html('<span class="match-text" id="PUESTO-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=divpol2022vallecali_view_parent]').hide(); } else { $j('.btn[id=divpol2022vallecali_view_parent]').show(); }


							if(typeof(PUESTO_update_autofills__RAND__) == 'function') PUESTO_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'concejo2019vallecalivotos', f: 'PUESTO' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_PUESTO__RAND__.value = e.added.id;
				AppGini.current_PUESTO__RAND__.text = e.added.text;
				$j('[name="PUESTO"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=divpol2022vallecali_view_parent]').hide(); } else { $j('.btn[id=divpol2022vallecali_view_parent]').show(); }


				if(typeof(PUESTO_update_autofills__RAND__) == 'function') PUESTO_update_autofills__RAND__();
			});

			if(!$j("#PUESTO-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_PUESTO__RAND__.value, t: 'concejo2019vallecalivotos', f: 'PUESTO' },
					success: function(resp) {
						$j('[name="PUESTO"]').val(resp.results[0].id);
						$j('[id=PUESTO-container-readonly__RAND__]').html('<span class="match-text" id="PUESTO-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=divpol2022vallecali_view_parent]').hide(); } else { $j('.btn[id=divpol2022vallecali_view_parent]').show(); }

						if(typeof(PUESTO_update_autofills__RAND__) == 'function') PUESTO_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_PUESTO__RAND__.value, t: 'concejo2019vallecalivotos', f: 'PUESTO' },
				success: function(resp) {
					$j('[id=PUESTO-container__RAND__], [id=PUESTO-container-readonly__RAND__]').html('<span class="match-text" id="PUESTO-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=divpol2022vallecali_view_parent]').hide(); } else { $j('.btn[id=divpol2022vallecali_view_parent]').show(); }

					if(typeof(PUESTO_update_autofills__RAND__) == 'function') PUESTO_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function PARTIDO_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#PARTIDO-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_PARTIDO__RAND__.value, t: 'concejo2019vallecalivotos', f: 'PARTIDO' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="PARTIDO"]').val(resp.results[0].id);
							$j('[id=PARTIDO-container-readonly__RAND__]').html('<span class="match-text" id="PARTIDO-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=partidos2022_view_parent]').hide(); } else { $j('.btn[id=partidos2022_view_parent]').show(); }


							if(typeof(PARTIDO_update_autofills__RAND__) == 'function') PARTIDO_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'concejo2019vallecalivotos', f: 'PARTIDO' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_PARTIDO__RAND__.value = e.added.id;
				AppGini.current_PARTIDO__RAND__.text = e.added.text;
				$j('[name="PARTIDO"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=partidos2022_view_parent]').hide(); } else { $j('.btn[id=partidos2022_view_parent]').show(); }


				if(typeof(PARTIDO_update_autofills__RAND__) == 'function') PARTIDO_update_autofills__RAND__();
			});

			if(!$j("#PARTIDO-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_PARTIDO__RAND__.value, t: 'concejo2019vallecalivotos', f: 'PARTIDO' },
					success: function(resp) {
						$j('[name="PARTIDO"]').val(resp.results[0].id);
						$j('[id=PARTIDO-container-readonly__RAND__]').html('<span class="match-text" id="PARTIDO-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=partidos2022_view_parent]').hide(); } else { $j('.btn[id=partidos2022_view_parent]').show(); }

						if(typeof(PARTIDO_update_autofills__RAND__) == 'function') PARTIDO_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_PARTIDO__RAND__.value, t: 'concejo2019vallecalivotos', f: 'PARTIDO' },
				success: function(resp) {
					$j('[id=PARTIDO-container__RAND__], [id=PARTIDO-container-readonly__RAND__]').html('<span class="match-text" id="PARTIDO-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=partidos2022_view_parent]').hide(); } else { $j('.btn[id=partidos2022_view_parent]').show(); }

					if(typeof(PARTIDO_update_autofills__RAND__) == 'function') PARTIDO_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/concejo2019vallecalivotos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/concejo2019vallecalivotos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return concejo2019vallecalivotos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return concejo2019vallecalivotos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return concejo2019vallecalivotos_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#MESA_').replaceWith('<div class=\"form-control-static\" id=\"MESA_\">' + (jQuery('#MESA_').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CANDIDATO').replaceWith('<div class=\"form-control-static\" id=\"CANDIDATO\">' + (jQuery('#CANDIDATO').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#VOTOS').replaceWith('<div class=\"form-control-static\" id=\"VOTOS\">' + (jQuery('#VOTOS').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(PUESTO)%%>', $combo_PUESTO->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(PUESTO)%%>', $combo_PUESTO->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(PUESTO)%%>', urlencode($combo_PUESTO->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(PARTIDO)%%>', $combo_PARTIDO->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(PARTIDO)%%>', $combo_PARTIDO->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(PARTIDO)%%>', urlencode($combo_PARTIDO->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['PUESTO' => ['divpol2022vallecali', 'PUESTO'], 'PARTIDO' => ['partidos2022', 'PARTIDO'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(CVOTOS)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(PUESTO)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(MESA)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(PARTIDO)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(MESA_)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CANDIDATO)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(VOTOS)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CVOTOS)%%>', safe_html($urow['CVOTOS']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CVOTOS)%%>', html_attr($row['CVOTOS']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CVOTOS)%%>', urlencode($urow['CVOTOS']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(PUESTO)%%>', safe_html($urow['PUESTO']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(PUESTO)%%>', html_attr($row['PUESTO']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PUESTO)%%>', urlencode($urow['PUESTO']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(MESA)%%>', safe_html($urow['MESA']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(MESA)%%>', html_attr($row['MESA']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(MESA)%%>', urlencode($urow['MESA']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(PARTIDO)%%>', safe_html($urow['PARTIDO']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(PARTIDO)%%>', html_attr($row['PARTIDO']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PARTIDO)%%>', urlencode($urow['PARTIDO']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(MESA_)%%>', safe_html($urow['MESA_']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(MESA_)%%>', html_attr($row['MESA_']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(MESA_)%%>', urlencode($urow['MESA_']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CANDIDATO)%%>', safe_html($urow['CANDIDATO']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CANDIDATO)%%>', html_attr($row['CANDIDATO']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CANDIDATO)%%>', urlencode($urow['CANDIDATO']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(VOTOS)%%>', safe_html($urow['VOTOS']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(VOTOS)%%>', html_attr($row['VOTOS']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VOTOS)%%>', urlencode($urow['VOTOS']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(CVOTOS)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CVOTOS)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(PUESTO)%%>', ( Request::val('FilterField')[1]=='2' && Request::val('FilterOperator')[1]=='<=>' ? $combo_PUESTO->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PUESTO)%%>', urlencode( Request::val('FilterField')[1]=='2' && Request::val('FilterOperator')[1]=='<=>' ? $combo_PUESTO->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%VALUE(MESA)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(MESA)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(PARTIDO)%%>', ( Request::val('FilterField')[1]=='4' && Request::val('FilterOperator')[1]=='<=>' ? $combo_PARTIDO->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PARTIDO)%%>', urlencode( Request::val('FilterField')[1]=='4' && Request::val('FilterOperator')[1]=='<=>' ? $combo_PARTIDO->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%VALUE(MESA_)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(MESA_)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CANDIDATO)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CANDIDATO)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(VOTOS)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(VOTOS)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('concejo2019vallecalivotos');
	if($selected_id) {
		$jdata = get_joined_record('concejo2019vallecalivotos', $selected_id);
		if($jdata === false) $jdata = get_defaults('concejo2019vallecalivotos');
		$rdata = $row;
	}
	$templateCode .= loadView('concejo2019vallecalivotos-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: concejo2019vallecalivotos_dv
	if(function_exists('concejo2019vallecalivotos_dv')) {
		$args = [];
		concejo2019vallecalivotos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}