<?php
// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/concejo2019vallecalivotos.php');
	include_once(__DIR__ . '/concejo2019vallecalivotos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('concejo2019vallecalivotos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'concejo2019vallecalivotos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`concejo2019vallecalivotos`.`CVOTOS`" => "CVOTOS",
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"`concejo2019vallecalivotos`.`MESA`" => "MESA",
		"IF(    CHAR_LENGTH(`partidos20221`.`partido`) || CHAR_LENGTH(`partidos20221`.`nompartido`), CONCAT_WS('',   `partidos20221`.`partido`, ' - ', `partidos20221`.`nompartido`), '') /* PARTIDO */" => "PARTIDO",
		"`concejo2019vallecalivotos`.`MESA_`" => "MESA_",
		"`concejo2019vallecalivotos`.`CANDIDATO`" => "CANDIDATO",
		"FORMAT(`concejo2019vallecalivotos`.`VOTOS`, 0)" => "VOTOS",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`concejo2019vallecalivotos`.`MESA_`',
		6 => 6,
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`concejo2019vallecalivotos`.`CVOTOS`" => "CVOTOS",
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"`concejo2019vallecalivotos`.`MESA`" => "MESA",
		"IF(    CHAR_LENGTH(`partidos20221`.`partido`) || CHAR_LENGTH(`partidos20221`.`nompartido`), CONCAT_WS('',   `partidos20221`.`partido`, ' - ', `partidos20221`.`nompartido`), '') /* PARTIDO */" => "PARTIDO",
		"`concejo2019vallecalivotos`.`MESA_`" => "MESA_",
		"`concejo2019vallecalivotos`.`CANDIDATO`" => "CANDIDATO",
		"FORMAT(`concejo2019vallecalivotos`.`VOTOS`, 0)" => "VOTOS",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"IF(    CHAR_LENGTH(`partidos20221`.`partido`) || CHAR_LENGTH(`partidos20221`.`nompartido`), CONCAT_WS('',   `partidos20221`.`partido`, ' - ', `partidos20221`.`nompartido`), '') /* PARTIDO */" => "PARTIDO",
		"`concejo2019vallecalivotos`.`CANDIDATO`" => "CANDIDATO",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
		"IF(    CHAR_LENGTH(`partidos20221`.`partido`) || CHAR_LENGTH(`partidos20221`.`nompartido`), CONCAT_WS('',   `partidos20221`.`partido`, ' - ', `partidos20221`.`nompartido`), '') /* PARTIDO */" => "PARTIDO",
		"`concejo2019vallecalivotos`.`CANDIDATO`" => "CANDIDATO",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['PUESTO' => 'PUESTO', 'PARTIDO' => 'PARTIDO', ];

	$x->QueryFrom = "`concejo2019vallecalivotos` LEFT JOIN `divpol2022vallecali` as divpol2022vallecali1 ON `divpol2022vallecali1`.`PUESTO`=`concejo2019vallecalivotos`.`PUESTO` LEFT JOIN `partidos2022` as partidos20221 ON `partidos20221`.`partido`=`concejo2019vallecalivotos`.`PARTIDO` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'concejo2019vallecalivotos_view.php';
	$x->TableTitle = 'Concejo';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`concejo2019vallecalivotos`.`CVOTOS`';

	$x->ColWidth = [10, 10, 10, ];
	$x->ColCaption = ['MESA ', 'CANDIDATO', 'VOTOS', ];
	$x->ColFieldName = ['MESA_', 'CANDIDATO', 'VOTOS', ];
	$x->ColNumber  = [5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/concejo2019vallecalivotos_templateTV.html';
	$x->SelectedTemplate = 'templates/concejo2019vallecalivotos_templateTVS.html';
	$x->TemplateDV = 'templates/concejo2019vallecalivotos_templateDV.html';
	$x->TemplateDVP = 'templates/concejo2019vallecalivotos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: concejo2019vallecalivotos_init
	$render = true;
	if(function_exists('concejo2019vallecalivotos_init')) {
		$args = [];
		$render = concejo2019vallecalivotos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: concejo2019vallecalivotos_header
	$headerCode = '';
	if(function_exists('concejo2019vallecalivotos_header')) {
		$args = [];
		$headerCode = concejo2019vallecalivotos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: concejo2019vallecalivotos_footer
	$footerCode = '';
	if(function_exists('concejo2019vallecalivotos_footer')) {
		$args = [];
		$footerCode = concejo2019vallecalivotos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
