<?php
// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/departamentos.php');
	include_once(__DIR__ . '/departamentos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('departamentos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'departamentos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`departamentos`.`dd`" => "dd",
		"`departamentos`.`departamento`" => "departamento",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`departamentos`.`dd`" => "dd",
		"`departamentos`.`departamento`" => "departamento",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`departamentos`.`dd`" => "Dd",
		"`departamentos`.`departamento`" => "Departamento",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`departamentos`.`dd`" => "dd",
		"`departamentos`.`departamento`" => "departamento",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`departamentos` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'departamentos_view.php';
	$x->TableTitle = 'Departamentos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`departamentos`.`dd`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Dd', 'Departamento', ];
	$x->ColFieldName = ['dd', 'departamento', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/departamentos_templateTV.html';
	$x->SelectedTemplate = 'templates/departamentos_templateTVS.html';
	$x->TemplateDV = 'templates/departamentos_templateDV.html';
	$x->TemplateDVP = 'templates/departamentos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: departamentos_init
	$render = true;
	if(function_exists('departamentos_init')) {
		$args = [];
		$render = departamentos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: departamentos_header
	$headerCode = '';
	if(function_exists('departamentos_header')) {
		$args = [];
		$headerCode = departamentos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: departamentos_footer
	$footerCode = '';
	if(function_exists('departamentos_footer')) {
		$args = [];
		$footerCode = departamentos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
