<?php
// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/municipios.php');
	include_once(__DIR__ . '/municipios_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('municipios');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'municipios';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`municipios`.`ddmm`" => "ddmm",
		"`municipios`.`dd`" => "dd",
		"`municipios`.`mm`" => "mm",
		"`municipios`.`municipio`" => "municipio",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`municipios`.`ddmm`" => "ddmm",
		"`municipios`.`dd`" => "dd",
		"`municipios`.`mm`" => "mm",
		"`municipios`.`municipio`" => "municipio",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`municipios`.`ddmm`" => "Ddmm",
		"`municipios`.`dd`" => "Dd",
		"`municipios`.`mm`" => "Mm",
		"`municipios`.`municipio`" => "Municipio",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`municipios`.`ddmm`" => "ddmm",
		"`municipios`.`dd`" => "dd",
		"`municipios`.`mm`" => "mm",
		"`municipios`.`municipio`" => "municipio",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`municipios` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'municipios_view.php';
	$x->TableTitle = 'Municipios';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`municipios`.`ddmm`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Ddmm', 'Dd', 'Mm', 'Municipio', ];
	$x->ColFieldName = ['ddmm', 'dd', 'mm', 'municipio', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/municipios_templateTV.html';
	$x->SelectedTemplate = 'templates/municipios_templateTVS.html';
	$x->TemplateDV = 'templates/municipios_templateDV.html';
	$x->TemplateDVP = 'templates/municipios_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: municipios_init
	$render = true;
	if(function_exists('municipios_init')) {
		$args = [];
		$render = municipios_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: municipios_header
	$headerCode = '';
	if(function_exists('municipios_header')) {
		$args = [];
		$headerCode = municipios_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: municipios_footer
	$footerCode = '';
	if(function_exists('municipios_footer')) {
		$args = [];
		$footerCode = municipios_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
