<?php
// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/partidos2022.php');
	include_once(__DIR__ . '/partidos2022_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('partidos2022');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'partidos2022';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`partidos2022`.`partido`" => "partido",
		"`partidos2022`.`nompartido`" => "nompartido",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`partidos2022`.`partido`" => "partido",
		"`partidos2022`.`nompartido`" => "nompartido",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`partidos2022`.`partido`" => "Partido",
		"`partidos2022`.`nompartido`" => "Nompartido",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`partidos2022`.`partido`" => "partido",
		"`partidos2022`.`nompartido`" => "nompartido",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`partidos2022` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'partidos2022_view.php';
	$x->TableTitle = 'Partidos2022';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`partidos2022`.`partido`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Partido', 'Nompartido', ];
	$x->ColFieldName = ['partido', 'nompartido', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/partidos2022_templateTV.html';
	$x->SelectedTemplate = 'templates/partidos2022_templateTVS.html';
	$x->TemplateDV = 'templates/partidos2022_templateDV.html';
	$x->TemplateDVP = 'templates/partidos2022_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: partidos2022_init
	$render = true;
	if(function_exists('partidos2022_init')) {
		$args = [];
		$render = partidos2022_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: partidos2022_header
	$headerCode = '';
	if(function_exists('partidos2022_header')) {
		$args = [];
		$headerCode = partidos2022_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: partidos2022_footer
	$footerCode = '';
	if(function_exists('partidos2022_footer')) {
		$args = [];
		$footerCode = partidos2022_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
