<?php
// This script and data application were generated by AppGini 23.15
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/testigospuestos.php');
	include_once(__DIR__ . '/testigospuestos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('testigospuestos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'testigospuestos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`testigospuestos`.`llave`" => "llave",
		"IF(    CHAR_LENGTH(`testigos1`.`CEDULA`) || CHAR_LENGTH(`testigos1`.`NOMBRE`), CONCAT_WS('',   `testigos1`.`CEDULA`, ' - ', `testigos1`.`NOMBRE`), '') /* CEDULA */" => "CEDULA",
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`testigospuestos`.`llave`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`testigospuestos`.`llave`" => "llave",
		"IF(    CHAR_LENGTH(`testigos1`.`CEDULA`) || CHAR_LENGTH(`testigos1`.`NOMBRE`), CONCAT_WS('',   `testigos1`.`CEDULA`, ' - ', `testigos1`.`NOMBRE`), '') /* CEDULA */" => "CEDULA",
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`testigospuestos`.`llave`" => "Llave",
		"IF(    CHAR_LENGTH(`testigos1`.`CEDULA`) || CHAR_LENGTH(`testigos1`.`NOMBRE`), CONCAT_WS('',   `testigos1`.`CEDULA`, ' - ', `testigos1`.`NOMBRE`), '') /* CEDULA */" => "CEDULA",
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`testigospuestos`.`llave`" => "llave",
		"IF(    CHAR_LENGTH(`testigos1`.`CEDULA`) || CHAR_LENGTH(`testigos1`.`NOMBRE`), CONCAT_WS('',   `testigos1`.`CEDULA`, ' - ', `testigos1`.`NOMBRE`), '') /* CEDULA */" => "CEDULA",
		"IF(    CHAR_LENGTH(`divpol2022vallecali1`.`PUESTO`) || CHAR_LENGTH(`divpol2022vallecali1`.`nompue`), CONCAT_WS('',   `divpol2022vallecali1`.`PUESTO`, ' - ', `divpol2022vallecali1`.`nompue`), '') /* PUESTO */" => "PUESTO",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['CEDULA' => 'CEDULA', 'PUESTO' => 'PUESTO', ];

	$x->QueryFrom = "`testigospuestos` LEFT JOIN `testigos` as testigos1 ON `testigos1`.`CEDULA`=`testigospuestos`.`CEDULA` LEFT JOIN `divpol2022vallecali` as divpol2022vallecali1 ON `divpol2022vallecali1`.`PUESTO`=`testigospuestos`.`PUESTO` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'testigospuestos_view.php';
	$x->TableTitle = 'Testigospuestos';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`testigospuestos`.`llave`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Llave', 'CEDULA', 'PUESTO', ];
	$x->ColFieldName = ['llave', 'CEDULA', 'PUESTO', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/testigospuestos_templateTV.html';
	$x->SelectedTemplate = 'templates/testigospuestos_templateTVS.html';
	$x->TemplateDV = 'templates/testigospuestos_templateDV.html';
	$x->TemplateDVP = 'templates/testigospuestos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: testigospuestos_init
	$render = true;
	if(function_exists('testigospuestos_init')) {
		$args = [];
		$render = testigospuestos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: testigospuestos_header
	$headerCode = '';
	if(function_exists('testigospuestos_header')) {
		$args = [];
		$headerCode = testigospuestos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: testigospuestos_footer
	$footerCode = '';
	if(function_exists('testigospuestos_footer')) {
		$args = [];
		$footerCode = testigospuestos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
